version: '3.9'

services:
  db:
    image: mysql:8.0.43
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: nginx:alpine
    container_name: webserver
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: